# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # This workflow contains a single job called "build"
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'
      
    - run: |
        cd flutter_app
        flutter pub get
#     - run: |
#         cd flutter_app
#         flutter test
    - run: |
        cd flutter_app
        flutter build apk
    - uses: actions/upload-artifact@v3
      with:
        name: android.apk
        path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
    - run: |
        cd flutter_app
        flutter build appbundle
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: android.apk
          path: ./Server/public/downloads
      - name: Deploy project with SSH
        uses : easingthemes/ssh-deploy@v2.1.4
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "./"
          TARGET: "~/PcController"
